### ISSUE TITLE
SQNomad-0.1.0 uninstallable  

### ISSUE THREAD

**Issue by 1ucian0** [scikit-quant/scikit-quant#13]
As reported in https://stackoverflow.com/questions/66644838/pip-install-r-requirements-dev-txt-error-command-errored-out-with-exit-st/66675330#66675330 `SQNomad-0.1.0` seems uninstallable, at least on MacOS.

**Comment by wlav** [comment]
Thanks for the report; I can reproduce it. Looking into it now.

**Comment by wlav** [comment]
Fixed in repo.

I was actually under the impression that qiskit installed the individual optimizers, not the container package. I'll make Nomad optional: it takes a long time to compile (hence the use of numpy's build setup).

**Comment by wlav** [comment]
And released.
