### ISSUE TITLE
SQNomad installation issue

### ISSUE THREAD

**Issue by prasadkumar0590** [scikit-quant/scikit-quant#15]
Could not build wheels for SQNomad which use PEP 517 and cannot be installed directl. Your help is very much appreciated!

System Specifications:
Python Version: 3.7
OS: Windows 10

**Comment by prasadkumar0590** [comment]
Could not build wheels for SQNomad which use PEP 517 and cannot be installed directly

System Specifications: 
Python Version:  3.7
OS: Windows 10

**Comment by wlav** [comment]
What does the actual error message show? There will be some message from distutils higher up, most likely (this being Windows) that you don't have a compiler installed?

**Comment by prasadkumar0590** [comment]
C:\Users\User1>python -m pip install SQNomad
Collecting SQNomad
  Using cached SQNomad-0.2.3.tar.gz (455 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting SQCommon
  Using cached SQCommon-0.3.2-py3-none-any.whl
Requirement already satisfied: numpy in c:\platform\oct-dist\python37\lib\site-packages (from SQNomad) (1.17.1+mkl)
Building wheels for collected packages: SQNomad
  Building wheel for SQNomad (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Platform\oct-dist\Python37\python.exe' 'C:\\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\AppData\Local\Temp\tmpy3sgo6g6'
       cwd: C:\Users\AppData\Local\Temp\pip-install-62nsruij\sqnomad_3e407c9e4c9741949cbf7dad3ccd5048
  Complete output (136 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  running build_src
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\SQNomad
  copying python\SQNomad\_nomad.py -> build\lib.win-amd64-3.7\SQNomad
  copying python\SQNomad\_version.py -> build\lib.win-amd64-3.7\SQNomad
  copying python\SQNomad\__init__.py -> build\lib.win-amd64-3.7\SQNomad
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using my_build_extension
  CCompilerOpt.cc_test_flags[999] : testing flags (/O2)
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils
  creating C:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks
  CCompilerOpt.cc_test_flags[999] : testing flags (/WX)
  CCompilerOpt.__init__[1147] : feature 'AVX512_KNL' is disabled, MSVC compiler doesn't support it
  CCompilerOpt.__init__[1147] : feature 'AVX512_KNM' is disabled, MSVC compiler doesn't support it
  CCompilerOpt.__init__[1674] : check requested baseline
  CCompilerOpt.cc_test_flags[999] : testing flags (/arch:SSE)
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[701] : Flags in command (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /TcC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\test_flags.c /FoC:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\test_flags.obj /arch:SSE) aren't supported by the compiler, output ->
  cl : Command line warning D9002 : ignoring unknown option '/arch:SSE'
  test_flags.c

  CCompilerOpt.cc_test_flags[1003] : testing failed
  CCompilerOpt.cc_test_flags[999] : testing flags (/arch:SSE2)
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[701] : Flags in command (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /TcC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\test_flags.c /FoC:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\test_flags.obj /arch:SSE2) aren't supported by the compiler, output ->
  cl : Command line warning D9002 : ignoring unknown option '/arch:SSE2'
  test_flags.c

  CCompilerOpt.cc_test_flags[1003] : testing failed
  CCompilerOpt.feature_test[1446] : testing feature 'SSE2' with flags ()
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[713] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /TcC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_sse2.c /FoC:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_sse2.obj /WX) failed with exit status 2 output ->
  cpu_sse2.c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\xmmintrin.h(75): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

  CCompilerOpt.feature_test[1458] : testing failed
  CCompilerOpt.feature_test[1446] : testing feature 'SSE' with flags ()
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[713] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /TcC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_sse.c /FoC:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_sse.obj /WX) failed with exit status 2 output ->
  cpu_sse.c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\xmmintrin.h(75): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

  CCompilerOpt.feature_test[1458] : testing failed
  CCompilerOpt.__init__[1683] : check requested dispatch-able features
  CCompilerOpt.feature_test[1446] : testing feature 'SSSE3' with flags ()
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[713] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /TcC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_ssse3.c /FoC:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_ssse3.obj /WX) failed with exit status 2 output ->
  cpu_ssse3.c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\xmmintrin.h(75): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

  CCompilerOpt.feature_test[1458] : testing failed
  CCompilerOpt.feature_test[1446] : testing feature 'SSE3' with flags ()
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[713] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /TcC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_sse3.c /FoC:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_sse3.obj /WX) failed with exit status 2 output ->
  cpu_sse3.c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\xmmintrin.h(75): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

  CCompilerOpt.feature_test[1458] : testing failed
  CCompilerOpt.cc_test_flags[999] : testing flags (/arch:AVX)
  CCompilerOpt.feature_test[1446] : testing feature 'F16C' with flags (/arch:AVX)
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[713] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /TcC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_f16c.c /FoC:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_f16c.obj /arch:AVX /WX) failed with exit status 2 output ->
  cpu_f16c.c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\xmmintrin.h(75): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

  CCompilerOpt.feature_test[1458] : testing failed
  CCompilerOpt.cc_test_flags[999] : testing flags (/arch:AVX2)
  CCompilerOpt.feature_test[1446] : testing feature 'FMA3' with flags (/arch:AVX2)
  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[713] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /TcC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_fma3.c /FoC:\Users\AppData\Local\Temp\tmpn2v1c03y\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\distutils\checks\cpu_fma3.obj /arch:AVX2 /WX) failed with exit status 2 output ->
  cpu_fma3.c
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\xmmintrin.h(75): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory

  CCompilerOpt.feature_test[1458] : testing failed
  CCompilerOpt.__init__[1699] : initialize targets groups
  CCompilerOpt.__init__[1701] : parse target group simd_test
  CCompilerOpt._parse_target_tokens[1912] : skip targets (SSE42 AVX512F NEON AVX512_SKX SSE2 VSX XOP FMA4 VSX2 VSX3 (FMA3 AVX2) ASIMD) not part of baseline or dispatch-able features
  CCompilerOpt.generate_dispatch_header[2236] : generate CPU dispatch header: (C:\Users\AppData\Local\Temp\src.win-amd64-3.7\numpy\distutils\include\npy_cpu_dispatch_config.h)
  Detected changes on compiler optimizations, force rebuilding
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  Missing compiler_cxx fix for MSVCCompiler
  customize MSVCCompiler using my_build_extension
  building 'libsqnomad' extension
  compiling C sources
  creating build\temp.win-amd64-3.7\Release\src
  creating build\temp.win-amd64-3.7\Release\src\Algos
  creating build\temp.win-amd64-3.7\Release\src\Cache
  creating build\temp.win-amd64-3.7\Release\src\Eval
  creating build\temp.win-amd64-3.7\Release\src\Math
  creating build\temp.win-amd64-3.7\Release\src\Output
  creating build\temp.win-amd64-3.7\Release\src\Param
  creating build\temp.win-amd64-3.7\Release\src\Python
  creating build\temp.win-amd64-3.7\Release\src\sgtelib
  creating build\temp.win-amd64-3.7\Release\src\Type
  creating build\temp.win-amd64-3.7\Release\src\Util
  creating build\temp.win-amd64-3.7\Release\src\Algos\LatinHypercubeSampling
  creating build\temp.win-amd64-3.7\Release\src\Algos\Mads
  creating build\temp.win-amd64-3.7\Release\src\Algos\NelderMead
  creating build\temp.win-amd64-3.7\Release\src\Algos\PhaseOne
  creating build\temp.win-amd64-3.7\Release\src\Algos\PSDMads
  creating build\temp.win-amd64-3.7\Release\src\Algos\QuadModel
  creating build\temp.win-amd64-3.7\Release\src\Algos\SgtelibModel
  creating build\temp.win-amd64-3.7\Release\src\Algos\SSDMads
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc -IC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\core\include -IC:\Users\AppData\Local\Temp\src.win-amd64-3.7\numpy\distutils\include -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /EHsc /Tpsrc\Algos\Algorithm.cpp /Fobuild\temp.win-amd64-3.7\Release\src\Algos\Algorithm.obj -IC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\core/include/numpy /std:c++14 /DDLL_EXPORTS /Zm1000
  Algorithm.cpp
  src\Algos\Algorithm.cpp(47): fatal error C1083: Cannot open include file: 'signal.h': No such file or directory

  ########### EXT COMPILER OPTIMIZATION ###########
  Platform      :
    Architecture: x64
    Compiler    : msvc

  CPU baseline  :
    Requested   : 'min'
    Enabled     : none
    Flags       : none
    Extra checks: none

  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : none
    Generated   : none
  CCompilerOpt._cache_write[796] : write cache to path -> C:\Users\AppData\Local\Temp\pip-install-62nsruij\sqnomad_3e407c9e4c9741949cbf7dad3ccd5048\build\temp.win-amd64-3.7\Release\ccompiler_opt_cache_ext.py
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc -IC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\core\include -IC:\Users\AppData\Local\Temp\src.win-amd64-3.7\numpy\distutils\include -IC:\Platform\oct-dist\Python37\include -IC:\Platform\oct-dist\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /EHsc /Tpsrc\Algos\Algorithm.cpp /Fobuild\temp.win-amd64-3.7\Release\src\Algos\Algorithm.obj -IC:\Users\AppData\Local\Temp\pip-build-env-l9fzttyk\overlay\Lib\site-packages\numpy\core/include/numpy /std:c++14 /DDLL_EXPORTS /Zm1000" failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for SQNomad
Failed to build SQNomad
ERROR: Could not build wheels for SQNomad which use PEP 517 and cannot be installed directly



This is the exact error. THank you

**Comment by prasadkumar0590** [comment]
> What does the actual error message show? There will be some message from distutils higher up, most likely (this being Windows) that you don't have a compiler installed?

Hi Wlav, Thank you for your quick reply. I have pasted exact error in separate comment. which compiler we need to install to work with SQNomad.

**Comment by wlav** [comment]
Closed means it worked out for you? The error (`Cannot open include file: 'malloc.h': No such file or directory`) does in deed indicate that the standard C headers are no installed or not located by the compiler.

As for which compiler: any recent (~5 years) MSVC should do. (Myself, I build with MSVC2017.) C++14 support is the minimum requirement.

**Comment by prasadkumar0590** [comment]
Hi wlav, I have installed MSVC2017 compiler. Still getting below error.

  Building wheel for SQNomad (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\IPMBOLT\Platform\oct-dist\Python37\python.exe' 'C:\IPMBOLT\Platform\oct-dist\Python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\pentipra\AppData\Local\Temp\tmpt557yeel'
       cwd: C:\Users\pentipra\AppData\Local\Temp\pip-install-a4jua35b\sqnomad_5451b5a0a8174dc9ba7c7b668dc15a48
  Complete output (20 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  running build_src
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\SQNomad
  copying python\SQNomad\_nomad.py -> build\lib.win-amd64-3.7\SQNomad
  copying python\SQNomad\_version.py -> build\lib.win-amd64-3.7\SQNomad
  copying python\SQNomad\__init__.py -> build\lib.win-amd64-3.7\SQNomad
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using my_build_extension
  CCompilerOpt.cc_test_flags[999] : testing flags (/O2)
  CCompilerOpt._cache_write[796] : write cache to path -> C:\Users\pentipra\AppData\Local\Temp\pip-install-a4jua35b\sqnomad_5451b5a0a8174dc9ba7c7b668dc15a48\build\temp.win-amd64-3.7\Release\ccompiler_opt_cache_ext.py
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for SQNomad

**Comment by wlav** [comment]
It's clearly not available in the environment where you're running `error: Microsoft Visual C++ 14.0 or greater is required.` Just on the command prompt, does running `cl.exe` work? If not, after installing MSVC, you should be able to find preset command prompt environments under the 'start' menu.
