### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by Q-lds** [scikit-quant/scikit-quant#21]
In the readme (and in pypi) you write `pip install sckit-quant`. However when I try installing through that command I get the following error 
```
ERROR: Could not find a version that satisfies the requirement sckit-quant
ERROR: No matching distribution found for sckit-quant
```

Could it be that you have a typo? It works fine if I try `pip install scikit-quant`.

**Comment by wlav** [comment]
Indeed; thanks for letting me know! Now fixed in repo, will show up shortly.
